{
  "props": {
    "singleton": true
  },
  "components": {
    "systemTray": {
      "type": "script\\SystemTrayScript",
      "x": 80,
      "y": 16,
      "props": {
        "visible": true,
        "tooltip": "TelegramRC Bot",
        "icon": ".data/img/remote_control.png",
        "manualExit": true,
        "alwaysShowing": true
      }
    },
    "robot": {
      "type": "script\\RobotScript",
      "x": 16,
      "y": 16,
      "props": {}
    }
  }
}